.PHONY: install first-sqlite-run first-mysql-run run

install:
	cd ./desafio/ && \
	pip install poetry && \
	poetry install


# OBS: use 'export' no Linux, 'set' no Windows
first-sqlite-run:
	set USE_SQLITE=True && \
	cd ./desafio/ && \
	poetry run python manage.py makemigrations app && \
	poetry run python manage.py migrate && \
	poetry run python manage.py runserver


# OBS: use 'export' no Linux, 'set' no Windows
first-mysql-run:
	set USE_SQLITE=False && \
	cd ./desafio/ && \
	poetry run python manage.py makemigrations app && \
	poetry run python manage.py migrate && \
	poetry run python manage.py runserver


run:
	cd ./desafio/ && \
	poetry run python manage.py runserver
